### ISSUE TITLE
Encoding problems with python

### ISSUE THREAD

**Issue by AlexanderYAPPO** [colotiline/Meduza.net#9]
Hello.

I'm trying to use meduza api but I have some problems with it.

For example, I'm getting a response with python urllib2 and decoding it in utf-8 since content-type says it is using utf-8. But I wasn't able to decode this correctly and I got decoding errors. Am I missing something or something is wrong with server response?

My code:

```
>>> import urllib2, json

>>> url = 'https://meduza.io/api/v3/feature/2015/03/11/ya-gotov-prinyat-lyuboy-rezhim-esli-razum-i-telo-budut-svobodny'
>>> res = urllib2.urlopen(url)
>>> encoding = res.headers['content-type'].split('charset=')[-1]
>>> print encoding
utf-8
>>> text = res.read().decode('utf-8')
Traceback (most recent call last):
  File "C:/Users/olskool/PycharmProjects/untitled/main/main.py", line 13, in <module>
    text = res.read().decode('utf-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by colotiline** [comment]
Hello, @AlexanderYAPPO. This is not Meduza official API repository. This is the repository of .net wrapper for it.
